index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeController::animales
    defaults: { nombre: 'Adrian', apellidos: 'Hoyos'}
    methods: [POST, GET]
    requirements:
        nombre: '[a-zA-Z]+'
        apellidos: '[0-9]+'

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir

animal_index:
    path: /animal/index
    controller: App\Controller\AnimalController::index

animal_detail:
    path: /animal/detail/{id}
    controller: App\Controller\AnimalController::animal

animal_update:
    path: /animal/update/{id}
    controller: App\Controller\AnimalController::update

animal_qb:
    path: /animal/qb
    controller: App\Controller\AnimalController::qb

animal_save:
    path: /animal/save
    controller: App\Controller\AnimalController::save
    methods: [POST]

crear_animal:
    path: /crear-animal
    controller: App\Controller\AnimalController::crearAnimal


